---
- hosts: all
  become: true
  tasks: 
    - name: update repository index
      apt: 
        update_cache: yes
    
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
    
    - name: add php support for apache
      apt: 
        name: libapache2-mod-php
        state: latest  

    - name: copy default site
      copy:
        src: default_site.html
        dest: var/www/html/index.html
        owner: root
        group: root
        mode: 0644